name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List root directory for debugging
      run: |
        pwd
        ls -lah

    - name: List files recursively for debugging
      run: |
        ls -R

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Google App Engine
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo $GCP_SA_KEY > ${HOME}/gcloud.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud --quiet config set project $GCP_PROJECT
        gcloud app deploy app.yaml --quiet
