# Generated by Django 5.0.6 on 2024-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convos', '0002_conversation_time_alter_conversation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
